Table User {
  id int [pk, increment]
  username varchar
  email varchar
  password varchar
  party_id int [ref: > Party.id, unique] // 1:1
}

Table Party {
  id int [pk, increment]
  name varchar
  level int
  experience int
  rating int
}

Table PartyCharacter {
  id int [pk, increment]
  party_id int [ref: > Party.id]
  character_id int [ref: > Character.id]
  party_slot int // 1-4

  Indexes {
    (party_id, party_slot) [unique]
  }
}

Table Character {
  id int [pk, increment]
  name varchar
  current_job_id int [ref: > Job.id]
}

Table Job {
  id int [pk, increment]
  name varchar
  icon varchar //route or path to icon image
}

Table Equipment {
  id int [pk, increment]
  name varchar
  type varchar // HEAD, CHEST, LEGS, PRIMARY_ARM, SECONDARY_ARM, ACCESSORY
  rating int
}

Table JobEquipment {
  id int [pk, increment]
  job_id int [ref: > Job.id]
  equipment_id int [ref: > Equipment.id]
  slot varchar

  Indexes {
    (job_id, slot) [unique]
  }
}
